language: python

python: 2.7
python: 3.4

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=pypy

matrix:
  exclude:
    - python: 2.7
      env: TOX_ENV=py34
    - python: 3.4
      env: TOX_ENV=flake8
    - python: 3.4
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=pypy

install:
    - pip install tox

script:
  - tox -e $TOX_ENV
